# log configuration for shat_gpt
logging:
  enabled: true
  format: "%(asctime)s.%(msecs)03d [%(levelname)s]: %(message)s"
  level: "INFO"

schemas:
  primary:
    embedding_fields: [
    "channel_name",
    "text",
    ]
    meta_data_fields: [
      "source",
      "user_id",
      "message_timestamp",
      "thread_timstamp",
      "channel_id",
      "thread_id",
    ]
    config:
      class: shat_index
      description: Some
      properties:
        - name: channel_name
          dataType: [text]
          moduleConfig:
            tokenizer: word
        - name: text
          dataType: [text]
          moduleConfig:
            tokenizer: word
        - name: source
          dataType: [text]
        - name: user_id
          dataType: [text]
        - name: message_timestamp
          dataType: [text]
        - name: thread_timstamp
          dataType: [text]
        - name: channel_id
          dataType: [text]
        - name: thread_id
          dataType: [text]
