# log configuration for shat_gpt
logging:
  enabled: true
  format: "%(asctime)s.%(msecs)03d [%(levelname)s]: %(message)s"
  level: "INFO"

schemas:
  primary:
    embedding_fields: [
    "channel_name",
    "text",
    ]
    meta_data_fields: [
      "source",
      "user_id",
      "message_timestamp",
      "thread_timstamp",
      "channel_id",
      "thread_id",
    ]
    config: {
    "class": "TextItem",
    "description": "A class called document",
    "vectorizer": "text2vec-openai",
    "moduleConfig": {
        "text2vec-openai": {"model": "ada", "modelVersion": "002", "type": "text"}
    },
    "properties": [
        {
            "name": "channel_name",
            "dataType": ["text"],
            "moduleConfig": {
                "text2vec-openai": {"skip": False, "vectorizePropertyName": True}
            },
        },
        {
            "name": "text",
            "dataType": ["text"],
            "moduleConfig": {
                "text2vec-openai": {"skip": False, "vectorizePropertyName": True}
            },
        },
        {
            "name": "source",
            "dataType": ["text"],
            "moduleConfig": {"text2vec-openai": {"skip": True}},
        },
        {
            "name": "user_id",
            "dataType": ["text"],
            "moduleConfig": {"text2vec-openai": {"skip": True}},
        },
        {
            "name": "message_timestamp",
            "dataType": ["text"],
            "moduleConfig": {"text2vec-openai": {"skip": True}},
        },
        {
            "name": "thread_timstamp",
            "dataType": ["text"],
            "moduleConfig": {"text2vec-openai": {"skip": True}},
        },
        {
            "name": "channel_id",
            "dataType": ["text"],
            "moduleConfig": {"text2vec-openai": {"skip": True}},
        },
        {
            "name": "thread_id",
            "dataType": ["text"],
            "moduleConfig": {"text2vec-openai": {"skip": True}},
        },
    ],
}
